robot_hardware:
  - joint_1_hw
  - joint_2_hw

joint_1_hw:
  type: ros_control_boilerplate/SimHWInterface
  joints:
    - joint1

  hardware_interface:
    joints:
      - joint1
    sim_control_mode: 0

joint_2_hw:
  type: ros_control_boilerplate/SimHWInterface
  joints:
    - joint2

  hardware_interface:
    joints:
      - joint2
    sim_control_mode: 0
